name: flashmaster
description: FlashMaster – Smart Flashcard Quiz App for students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Database
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: any
  path: ^1.9.0

  # UI & Charts
  fl_chart: ^0.68.0
  confetti: ^0.7.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1

  # Utilities
  shared_preferences: ^2.2.3
  uuid: ^4.4.2
  intl: ^0.19.0
  path_provider: ^2.1.3

  # Export / Import
  pdf: ^3.10.8
  printing: ^5.13.1
  file_picker: ^8.1.2
  share_plus: ^12.0.2

  # Notifications
  flutter_local_notifications: ^17.2.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  # No local fonts needed since google_fonts package is used.
